# Generated by Django 4.1.6 on 2023-03-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=120)),
                ('description', models.TextField(blank=True, default='N/A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.fact')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=120)),
                ('origin', models.CharField(default='N/A', max_length=120)),
                ('availability', models.CharField(default='N/A', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facts', models.ManyToManyField(through='pantries.FactInfo', to='pantries.fact')),
            ],
            options={
                'ordering': ['info_id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('related_name', models.CharField(default='N/A', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.info')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('nutrition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=120)),
                ('water', models.CharField(default='N/A', max_length=120)),
                ('fiber', models.CharField(default='N/A', max_length=120)),
                ('vitamins', models.CharField(default='N/A', max_length=120)),
                ('minerals', models.CharField(default='N/A', max_length=120)),
                ('carbs', models.CharField(default='N/A', max_length=120)),
                ('lipids', models.CharField(default='N/A', max_length=120)),
                ('proteins', models.CharField(default='N/A', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nutrition_id'],
            },
        ),
        migrations.CreateModel(
            name='Pantrie',
            fields=[
                ('pantrie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('quantity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.ingredient')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='QuantityRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('related_name', models.CharField(default='N/A', max_length=120)),
                ('preparation', models.TextField(blank=True)),
                ('preparation_time', models.FloatField(default=0)),
                ('difficulty', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantities', models.ManyToManyField(through='pantries.QuantityRecipe', to='pantries.quantity')),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Temperature', (('Celcius', '°C'), ('Farenheit', '°F'))), ('Time', (('Seconds', 's'), ('Minutes', 'm'), ('Hours', 'h'), ('Days', 'd'), ('Weeks', 'w'))), ('Mass', (('Grams', 'g'), ('Kilograms', 'kg'))), ('Volume', (('Litre', 'l'), ('Mililitre', 'ml'))), ('Amount', (('Unit', 'u'), ('Spoon', 'spn')))], default='Unit', max_length=18, unique=True)),
                ('related_name', models.CharField(default='N/A', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipePantrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pantrie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.pantrie')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='quantityrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.recipe'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.unit'),
        ),
        migrations.AddField(
            model_name='pantrie',
            name='recipes',
            field=models.ManyToManyField(through='pantries.RecipePantrie', to='pantries.recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.nutrition'),
        ),
        migrations.AddField(
            model_name='factinfo',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.info'),
        ),
    ]
