# Generated by Django 4.1.6 on 2023-03-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('related_name', models.CharField(default='N/A', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pantrie',
            fields=[
                ('pantrie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('quantity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.ingredient')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('related_name', models.CharField(default='N/A', max_length=120)),
                ('preparation', models.TextField(blank=True)),
                ('preparation_time', models.FloatField(default=0)),
                ('difficulty', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Mass', (('Grams', 'g'), ('Kilograms', 'kg'))), ('Volume', (('Litre', 'l'), ('Mililitre', 'ml'))), ('Amount', (('Unit', 'u'), ('Spoon', 'spn')))], default='Unit', max_length=18, unique=True)),
                ('related_name', models.CharField(default='N/A', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipePantrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pantrie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.pantrie')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.quantity')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='quantity',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantries.unit'),
        ),
        migrations.AddField(
            model_name='pantrie',
            name='recipes',
            field=models.ManyToManyField(through='pantries.RecipePantrie', to='pantries.recipe'),
        ),
    ]
