# Generated by Django 4.1.6 on 2023-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.IntegerField(choices=[(0, 'Minutes'), (1, 'Minutes'), (2, 'Hours'), (3, 'Days'), (4, 'Weeks')], default=0),
        ),
    ]
