# Generated by Django 4.1.6 on 2023-03-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantities',
            field=models.ManyToManyField(through='pantries.QuantityRecipe', to='pantries.quantity'),
        ),
    ]
