# Generated by Django 4.1.6 on 2023-02-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0004_ingredient_quantity_ingredient_quantity_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
    ]
