# Generated by Django 4.1.6 on 2023-02-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0005_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_unit',
            field=models.CharField(choices=[('Litre', 'Litre'), ('Mililitre', 'Mililitre'), ('Grams', 'Grams'), ('Kilograms', 'Kilograms'), ('Unit', 'Unit'), ('Spoon', 'Spoon'), ('Piece', 'Piece')], default='Kilograms', max_length=10),
        ),
    ]
