# Generated by Django 4.1.6 on 2023-02-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0007_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='related_name',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
