# Generated by Django 4.1.6 on 2023-02-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0008_recipe_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='related_name',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
